### ISSUE TITLE
all figures as vector PDFs

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/siweed#103]
Use, e.g., MATLAB's [`exportgraphics command.`](https://www.mathworks.com/help/matlab/ref/exportgraphics.html#mw_8cf87574-e18a-4f05-b69a-dcab95ae28da)

**Comment by ryancoe** [comment]
@nickross4444 - is this complete?

**Comment by nickross4444** [comment]
I was going to wait until I had the PD verification graphics finalized to close the issue. Besides that, yes.

**Comment by ryancoe** [comment]
I'll consider it closed since the paper does indeed use only `pdf` figures, we can address #102 separately
