### ISSUE TITLE
Noise in Wave Probe Signal

### ISSUE THREAD

**Issue by nickross4444** [SNL-WaterPower/siweed#3]
Can be reduced by configuring the Wave Probe to not use RS232 communications. Can also be improved with a filter in processing.

**Comment by ryancoe** [comment]
@nickross4444 - did you complete this?

**Comment by nickross4444** [comment]
We decided to switch from the analog read out to the digital one. The prototyped code was tested, but it has not been tested with the full system yet. Likely will be this Thursday.

**Comment by nickross4444** [comment]
Tested. Required a moving average, but now looks good.

**Comment by ryancoe** [comment]
@nickross4444 Could you post a plot of the improved signal?

**Comment by nickross4444** [comment]
This is from #107 
![image](https://user-images.githubusercontent.com/42656158/143660673-0ef8ca24-baf3-46f5-a1e5-7bc763ace857.png)
The yellow line is the improved signal. The moving average is one I threw together in java that averages the last 10 samples. The number of samples is variable.

**Comment by ryancoe** [comment]
Ok, looks like we can deal with #107 separately.

10 samples at what sample rate?

**Comment by nickross4444** [comment]
The wave probes have been configured to output at 30hz
