### ISSUE TITLE
CSV data

### ISSUE THREAD

**Issue by nickross4444** [SNL-WaterPower/siweed#82]
We've decided to leave csv logs in this github issue for storage. Attached are the first two sets.
[test logs.zip](https://github.com/SNL-WaterPower/siweed/files/6542033/test.logs.zip)

**Comment by ryancoe** [comment]
@nickross4444 - this works well. I would suggest a minor tweak: post the data the pertains to a specific discussion (e.g., post the data for calculating the torque constant in #59).
