### ISSUE TITLE
Survey of other small scale wave tanks

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/siweed#83]
For our HarwareX paper, I'd like to do a quick review of other small scale wave tanks out there:

https://github.com/SNL-WaterPower/siweed/blob/919908d0400da31c2c2407996ca2bd9713debb87/documentation/siweedPaper.tex#L109-L111

**Comment by ryancoe** [comment]
@delaneyheileman - Friendly reminder that it'd be great if you can add to this before heading out ;)

**Comment by nickross4444** [comment]
@ryancoe, please read and validate the changes in 795173358b4ecd8f71ef90b676b6997a9014d5ee

**Comment by ryancoe** [comment]
Looks good!
