### ISSUE TITLE
Add system diagram to paper

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/siweed#84]
https://github.com/SNL-WaterPower/siweed/blob/919908d0400da31c2c2407996ca2bd9713debb87/documentation/siweedPaper.tex#L117-L118

**Comment by nickross4444** [comment]
@ryancoe Do you just want the System layout diagram we have in the Readme to be in the paper?

**Comment by ryancoe** [comment]
Yes (or new version of it).
