### ISSUE TITLE
Update bill of materials and add to paper

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/siweed#85]
https://github.com/SNL-WaterPower/siweed/blob/919908d0400da31c2c2407996ca2bd9713debb87/documentation/siweedPaper.tex#L187-L208

**Comment by nickross4444** [comment]
It will need to be converted to a PDF and uploaded before uploading the paper, but the content is finished in a spreadsheet.

**Comment by ryancoe** [comment]
May be helpful: https://ctan.org/tex-archive/support/excel2latex?lang=en

**Comment by ryancoe** [comment]
@nickross4444 - per our discussion today, please break out the BOM so that we have totals for:

1. All parts except computer and tank
2. Computer and tank
3. 1+2

Please also add a sentence to the paper along the lines of _Note that a SIWEED system can be assembled with any tank on hand (e.g., a fish tank) and any MS Windows PC running; as these components can contribute significantly to system cost, the BOM shown in Table XX lists the tank and computer separately from the remainder of the components._

**Comment by nickross4444** [comment]
- [ ] Add beach decorations to BOM, in a separate section.

**Comment by nickross4444** [comment]
- [ ] Add V2 order to BOM
- [ ] Format nicely.

**Comment by nickross4444** [comment]
@Anwi505, could you update the links in the BOM to model numbers?

**Comment by ryancoe** [comment]
@nickross4444 - I've updated the [`BOM.csv`](https://github.com/SNL-WaterPower/siweed/blob/master/documentation/BOM.csv) with [c1e42da](https://github.com/SNL-WaterPower/siweed/commit/c1e42da1eddf0b0589be438d6f492c54434de541). Can you check that the "V2 order" has been incorporated per [your checkbox above](https://github.com/SNL-WaterPower/siweed/issues/85#issuecomment-892846999); after that we may want to make a separate issue about putting a link in the paper, as there will be a tricky order of operations things there (new branch, release, add link to BOM, make Zenodo tag).
