### ISSUE TITLE
Target audience

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/siweed#88]
@delaneyheileman - has asked a question about the target audience

**current target audience:** college students and above
**future expansion:** tailor GUI more towards younger students (e.g., make a "basic" mode for the GUI that reduced the number of inputs)

**Comment by ryancoe** [comment]
@nickross4444 - Can you please add a sentence to the paper clarifying who our target audience is?

**Comment by nickross4444** [comment]
As a note, the basic/limited gui is finished on the develop branch.

**Comment by ryancoe** [comment]
Oh very interesting!
