### ISSUE TITLE
Basic mode for GUI

### ISSUE THREAD

**Issue by ryancoe** [SNL-WaterPower/siweed#89]
From #88, we would like to consider adding a switch to the GUI which will change the layout of the GUI. The idea would be to reduce the number of user inputs from ~12 down to ~2 (e.g., wave height and wave period) so that an elementary school student would feel comfortable.

_(this is a long-term goal)_

**Comment by nickross4444** [comment]
Finished earlier today

**Comment by ryancoe** [comment]
fastest completion of an issue _ever_

**Comment by nickross4444** [comment]
![image](https://user-images.githubusercontent.com/42656158/122479512-6f9d1700-cf88-11eb-90e7-b9e1182ffde9.png)

**Comment by ryancoe** [comment]
very nice!
