### ISSUE TITLE
Pop up boxes

### ISSUE THREAD

**Issue by nickross4444** [SNL-WaterPower/siweed#90]
Graphic design isn't my strong suit, so please give me some feedback to make these boxes look better:
![image](https://user-images.githubusercontent.com/42656158/122611927-6f138780-d03f-11eb-93c0-1aecf305e4eb.png)
![image](https://user-images.githubusercontent.com/42656158/122611942-75a1ff00-d03f-11eb-9a04-0e3e62399c17.png)

The text in the boxes can be modified easily by editing the text files in siweed\Processing\siWeedGUI\data. @ryancoe, if it is important that these are YAML files, let me know and I can try to make it work, but YAML doesn't seem to play well with java.

**Comment by ryancoe** [comment]
@nickross4444 - per our discussion today, please:

- [ ] add pop-ups for all of the plots
- [ ] use a single text file to load the messages for these pop-ups

**Comment by nickross4444** [comment]
- [ ] Improve the look of the boxes.

**Comment by nickross4444** [comment]
I think the pop up boxes look fine now:

![image](https://user-images.githubusercontent.com/42656158/124801724-657d9100-df14-11eb-9aa2-3014e2c70dd1.png)

@ryancoe , could you check and modify the language in them, so we can close this issue?

**Comment by nickross4444** [comment]
Also a note that the buttons are now bigger and color matching:
![image](https://user-images.githubusercontent.com/42656158/124841117-c5425f00-df49-11eb-894a-cee87dbf7996.png)

**Comment by ryancoe** [comment]
@nickross4444 - what branch should I be looking at for this?

**Comment by nickross4444** [comment]
In develop [here](https://github.com/SNL-WaterPower/siweed/blob/develop/Processing/siWeedGUI/data/popUpText.txt)

**Comment by ryancoe** [comment]
Ok, I've made some minor updates with bd2a6388717cecadc7f27a517dba61e48776e347. I think we can close this for now.
